### PR TITLE
Fix error 404

### PR DESCRIPTION
**Pull request by Aerilius**
For some urls, the onebox was not generated anymore, instead, the browser console showed a 404 error:

https://3dwarehouse.sketchup.com/model.html?id=a745c0ce-67bd-4cc6-b6c0-f65949915d6e

```
GET http://forums.sketchup.com/onebox?url=https%3A%2F%2F3dwarehouse.sketchup.com%2Fmodel.html%3Fid%3Da745c0ce-67bd-4cc6-b6c0-f65949915d6e&refresh=true 404 (Not Found)
```

The error was thrown by discourse not finding a matching onebox (see comment in `discourse/app/controllers/onebox_controller.rb:10`). It seems the 3D Warehouse url `id` parameter omits since some time the `u` in front of the new longer IDs so that the regular expression did not match anymore.

As a solution I made the `[uU]` optional.

### CODE REVIEW

**Comment by Aerilius** [comment]
By the way, during testing the error was not gone immediately because `Rails.catch.fetch` still returned a `blank_onebox`. I had to:
```
bundle exec rails c
Rails.cache.clear
exit
```

**Comment by thomthom** [comment]
I'm trying to figure out who's handling the management of the plugin.

**Comment by Aerilius** [comment]
Need to ask Roy whether the new url structure also affects `/3dw/GetEntity?id=#{id}` (riking wrote that part).

**Comment by bjanzen** [comment]
Nope, it wont affect that.  Thanks.

**Comment by rchanley** [comment]
Hi guys,

My apologies in the time its taking to get to this.  In order to get this fix onto the SketchUp forums, we'll need to get this fix into Discourse's fork of this repository: https://github.com/discourse/discourse-sketchup-3dwh-onebox

And to do that, I believe we need to first get this pull request approved here, then have the Discourse folks sync up with this project.

@thomthom, can you please approve this pull request?  Here's a relevant thread if you're out of the loop: https://forums.sketchup.com/t/how-to-embed-3d-warehose-models-directly-in-this-forum/41634/3

**Pull request merged**
